# Generated by Django 6.1.1 on 2026-09-20 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Género')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio ($)')),
            ],
        ),
    ]
