# Generated by Django 6.1.1 on 2026-09-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0002_editorial_genero_remove_libro_id_and_more'),
    ]

    operations = [
        # Orden reordenado a mano: primero se le quita la PK a isbn y recién
        # después se crea id como PK. MariaDB no permite dos PK a la vez
        # ("Multiple primary key defined"), y el autodetector generaba AddField antes.
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=13, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='libro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
